//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int IdContacto { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdUsuarioContacto { get; set; }
        public string Alias { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoUsuario
    {
        public int IdEstado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<bool> EstaEnLinea { get; set; }
        public Nullable<System.DateTime> UltimaConexion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialConversacion
    {
        public int IdHistorial { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdConversacionCon { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuperacionPassword
    {
        public int IdRecuperacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TokenRecuperacion { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public int IdRol { get; set; }
        public string NombreRol { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenSesion
    {
        public int IdTokenSesion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Contacto1 = new HashSet<Contacto>();
            this.EstadoUsuario = new HashSet<EstadoUsuario>();
            this.HistorialConversacion = new HashSet<HistorialConversacion>();
            this.HistorialConversacion1 = new HashSet<HistorialConversacion>();
            this.Mensaje = new HashSet<EntidadMensaje>();
            this.Mensaje1 = new HashSet<EntidadMensaje>();
            this.RecuperacionPassword = new HashSet<RecuperacionPassword>();
            this.TokenSesion = new HashSet<TokenSesion>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public int IdUsuario { get; set; }
        public string Correo { get; set; }
        public string ContrasenaHash { get; set; }
        public string NombreCompleto { get; set; }
        public byte[] FotoPerfil { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoUsuario> EstadoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialConversacion> HistorialConversacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialConversacion> HistorialConversacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadMensaje> Mensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadMensaje> Mensaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecuperacionPassword> RecuperacionPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenSesion> TokenSesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRol
    {
        public int IdUsuario { get; set; }
        public int IdRol { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class sp_helpdiagramdefinition_Result
    {
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class sp_helpdiagrams_Result
    {
        public string Database { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public string Owner { get; set; }
        public int OwnerID { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class spObtenerMensaje_Result
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class spObtenerMensajesPorConversacion_Result
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class spObtenerMensajesPorEstado_Result
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class spObtenerMensajesPorUsuario_Result
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
namespace AccesoDatos
{
    using System;
    
    public partial class spObtenerTodosLosMensajes_Result
    {
        public int IdMensaje { get; set; }
        public Nullable<int> IdRemitente { get; set; }
        public Nullable<int> IdDestinatario { get; set; }
        public string Contenido { get; set; }
        public Nullable<bool> Editado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
