//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion.LNMensajes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadMensaje", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EntidadMensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EditadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRemitenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Editado {
            get {
                return this.EditadoField;
            }
            set {
                if ((this.EditadoField.Equals(value) != true)) {
                    this.EditadoField = value;
                    this.RaisePropertyChanged("Editado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActualizacion {
            get {
                return this.FechaActualizacionField;
            }
            set {
                if ((this.FechaActualizacionField.Equals(value) != true)) {
                    this.FechaActualizacionField = value;
                    this.RaisePropertyChanged("FechaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEnvio {
            get {
                return this.FechaEnvioField;
            }
            set {
                if ((this.FechaEnvioField.Equals(value) != true)) {
                    this.FechaEnvioField = value;
                    this.RaisePropertyChanged("FechaEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDestinatario {
            get {
                return this.IdDestinatarioField;
            }
            set {
                if ((this.IdDestinatarioField.Equals(value) != true)) {
                    this.IdDestinatarioField = value;
                    this.RaisePropertyChanged("IdDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMensaje {
            get {
                return this.IdMensajeField;
            }
            set {
                if ((this.IdMensajeField.Equals(value) != true)) {
                    this.IdMensajeField = value;
                    this.RaisePropertyChanged("IdMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRemitente {
            get {
                return this.IdRemitenteField;
            }
            set {
                if ((this.IdRemitenteField.Equals(value) != true)) {
                    this.IdRemitenteField = value;
                    this.RaisePropertyChanged("IdRemitente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LNMensajes.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorFecha", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorFechaResponse")]
        Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorFecha(System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorFecha", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorFechaResponse")]
        System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorFechaAsync(System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorUsuario", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorUsuarioResponse")]
        Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorUsuario(int id_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorUsuario", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorUsuarioResponse")]
        System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorUsuarioAsync(int id_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorPalabras", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorPalabrasResponse")]
        Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorPalabras(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Recuperar_HistorialPorPalabras", ReplyAction="http://tempuri.org/IService/Recuperar_HistorialPorPalabrasResponse")]
        System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorPalabrasAsync(string palabra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Aplicacion.LNMensajes.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Aplicacion.LNMensajes.IService>, Aplicacion.LNMensajes.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorFecha(System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.Recuperar_HistorialPorFecha(fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorFechaAsync(System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.Recuperar_HistorialPorFechaAsync(fechaInicio, fechaFin);
        }
        
        public Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorUsuario(int id_Usuario) {
            return base.Channel.Recuperar_HistorialPorUsuario(id_Usuario);
        }
        
        public System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorUsuarioAsync(int id_Usuario) {
            return base.Channel.Recuperar_HistorialPorUsuarioAsync(id_Usuario);
        }
        
        public Aplicacion.LNMensajes.EntidadMensaje[] Recuperar_HistorialPorPalabras(string palabra) {
            return base.Channel.Recuperar_HistorialPorPalabras(palabra);
        }
        
        public System.Threading.Tasks.Task<Aplicacion.LNMensajes.EntidadMensaje[]> Recuperar_HistorialPorPalabrasAsync(string palabra) {
            return base.Channel.Recuperar_HistorialPorPalabrasAsync(palabra);
        }
    }
}
